### ISSUE TITLE
Add SSL certificate pinning

### ISSUE THREAD

**Issue by chengfred** [Simperium/simperium-android#114]
Since we only ever connect to simperium.com we should pin the ssl certificate

https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning

**Comment by beaucollins** [comment]
Should we make this somewhat configurable since perhaps someday people might run their on server stack?

**Comment by chengfred** [comment]
Yeah definitely. 

Some [tradeoffs outlined](http://blog.lumberlabs.com/2012/04/why-app-developers-should-care-about.html) which suggests [pinning to hash of SPKI](https://www.imperialviolet.org/2011/05/04/pinning.html).

cc: Simperium/simperium-ios#282

**Comment by beaucollins** [comment]
[Android docs related to SSL/TLS](http://developer.android.com/training/articles/security-ssl.html#Pinning). Mentions pinning and detecting certificates.

**Comment by beaucollins** [comment]
More info on implementing pinning: https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning#Android

**Comment by beaucollins** [comment]
Looking at using [Android Pinning](https://github.com/moxie0/AndroidPinning) to provide pinning logic. Found via the [author's article on pinning and ssl](http://www.thoughtcrime.org/blog/authenticity-is-broken-in-ssl-but-your-app-ha/) which in turn references the blog about [pinning in Chrome](https://www.imperialviolet.org/2011/05/04/pinning.html).

I should be able to use the `PinningTrustManager` directly.

@fredrocious does this look sufficient? I'll need the encoded SPKI from simperium.com's pem certificate.

**Comment by beaucollins** [comment]
The Android Pinning library provides a [python script that generates the SPKI](https://github.com/moxie0/AndroidPinning/blob/master/tools/pin.py).

**Comment by chengfred** [comment]
:fireworks:
