### ISSUE TITLE
Duplicate rows in index table

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#116]
Noticed in Simplenote that I occasionally get duplicated notes. Manages to grab the db and noticed that the index table had duplicate values:

![screen shot 2014-06-05 at 11 43 43 am](https://cloud.githubusercontent.com/assets/789137/3192107/2f9c24f6-ece2-11e3-80c3-b960310d9aa6.png)

Seems there's two things to fix: 
1. Make sure one index operation is run at a time and that it doesn't allow duplicate records in the table.
2. Add ~~`UNIQUE`~~ `DISTINCT` to the QueryBuilder query to ensure we don't return dupes.

**Comment by beaucollins** [comment]
Duplicate rows in the index table isn't necessarily incorrect.

If you had a model that contained a property that was a list of strings, and it listed the same string twice it would index the string two times. That data could potentially be used to query against.

**Comment by roundhill** [comment]
OK, I won't change anything about data insertion but will clear the reindex_queue table at startup.

**Comment by beaucollins** [comment]
Perhaps we need to create a Simperium syncing service that activities can bind to so we know there's only one instance of Simperium running.

**Comment by roundhill** [comment]
That would probably help a lot!
