### ISSUE TITLE
Send final modifications before removing an object from a bucket

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#159]
An object should send all pending modifications before it is removed from the bucket.

**Comment by beaucollins** [comment]
After some testing this appears to be the issue:
1. Bucket object is modified and saved but not yet sent `BucketObject.save()`
2. Bucket object is removed from bucket `BucketObject.remove()`
3. Change processor kicks in to send the modification change
4. Change processor tries to query for object to produce the diff but it no longer exists in the local persistent store due to step 2
5. Modification attempt throws `ChangeNotSentException`
6. Remove operation is sent

To resolve this we probably need to copy the data to diff during the modification operation so the storage system doesn't need to be queried. This will also solve #158.

**Comment by roundhill** [comment]
There's a fair amount of crashes in the WordPress client for #158. Think you could knock this one out soon?

**Comment by roundhill** [comment]
> fair amount of crashes

And by fair, i mean 14 so far in 3.3 so not terrible.
