### ISSUE TITLE
ChangeProcessor Thread needs to block or die

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#16]
Currently it loops indefinitely and is pegging CPU and/or killing battery.

Some kind of combination of ArrayBlockingQueue and Thread.interrupt should do the trick for now.

**Comment by beaucollins** [comment]
[The offending method is Channel.ChangeProcessor.run()](https://github.com/Simperium/simperium-android/blob/6fa70a6e4/Simperium/src/main/java/com/simperium/client/Channel.java#L887-L905).

**Comment by roundhill** [comment]
Let's get this in before the RC :)
