### ISSUE TITLE
Change queue saving not functioning when app is killed

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#25]
It there are local changes queued and the app is killed, the app doesn't have a change to serializer the queue correctly.

Need to serialize the queue as changes to it are made.

The ChangeProcessor needs to stay performant so saving to a file probably is not the best solution.

**Comment by mikejohnstn** [comment]
Perhaps learning from my mistakes: over on iOS, we have an issue to make all serialization atomic with datastore writes: https://github.com/Simperium/simperium-ios/issues/124

This will likely involve transparently injecting some extra data into the datastore.

Also related, on Mac I ended up delaying termination of the app ever so briefly so the Simperium threads could properly bail and serialize. Not great, but it works for now: https://github.com/Simperium/simplenote-osx/blob/master/Simplenote/SimplenoteAppDelegate.m#L465

**Comment by beaucollins** [comment]
That's essentially the approach I'm going with now and was originally how the library was working.

We are still using a pretty crufty dump of JSON to serialize the queue which is horrible for performance. Moving the sync status to the db should give us the performance we need to make it atomic with database writes.
