### ISSUE TITLE
Local callback triggered by a local update?

### ISSUE THREAD

**Issue by cristiano-belloni** [Simperium/simperium-android#38]
See this [stackoverflow question](http://stackoverflow.com/questions/19115085/local-callback-in-simperium-triggered-by-a-local-update).

**Comment by beaucollins** [comment]
@janesconference this is the java/android library and it looks like the Stackoverflow question is specifically for the Javascript library so I'm going to close the ticket.

The Javascript library is maintained here: https://github.com/Simperium/simperium-js

I'll take a look at your SO question, hopefully we can get it sorted out!
