### ISSUE TITLE
Post OnNetworkChange notifications while downloading an index

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#4]
Bucket.OnNetworkChange listeners aren't being notified of changes until after a bucket has been loaded with an index. Listeners should be updated as objects are saved to the index.

**Comment by mikejohnstn** [comment]
On iOS I decided to go with batches of 10 to ease the strain on the main thread, with instant notifications once you get to 10 or less (or if you're starting with less than 10). Logic here if you think it's relevant: https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPWebSocketChannel.m#L410

**Comment by chengfred** [comment]
Let me know if you find server response times are contributing to TTFN
