### ISSUE TITLE
Syncing delete operations should not clear pending modify operations

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#42]
Example with Simplenote:

When a user is offline and they:
1. Move the note to trash
2. Empty the trash
3. Client reconnects and syncs

Step 1 causes a modify operation to set `deleted` to `true`.

Step 2 created a delete operation which causes all queued modify operations to be discarded by the client

Step 3 the delete operation is sent but fails because the bucket schema requires the `deleted` property to be `true` before it will allow an object to be deleted.

**Comment by beaucollins** [comment]
One edge case to consider: an object is created, possibly modified, then deleted all while disconnected. Should any of those operations be sent out?

**Comment by chengfred** [comment]
I say no in that case, can't think of arguments for the pro.
FWIW, when retrieving changes from server, by default we also omit the operations for the case you mention https://github.com/Simperium/poutine/blob/master/poutine/server/index.py#L536-L539
