### ISSUE TITLE
Applying remote changes to a locally modified object should produce a rebased value for text values

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#67]
Example:

App has  a note model. User modifies the note content. Before the local modification is synced, another client modifies and syncs the same note's content.

Since both values of the content are strings, the local modification should do it's best to produce a three way merge of the content.

See https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPMemberText.m#L66-L91

**Comment by chengfred** [comment]
Also see https://github.com/Simperium/simperium-js/blob/master/sync.coffee#L415-L427

**Comment by beaucollins** [comment]
Actual implementation is here: https://github.com/Simperium/jsondiff/blob/eb61ad1e4554450cc14af1938847f18513db946b/src/jsondiff.coffee#L458-L503

**Comment by beaucollins** [comment]
Looks like the iOS library doesn't handle as many transform cases as the javascript library. The critical feature appears to be merging diff_match_patch operations.
